### ISSUE TITLE
library.properties is stale

### ISSUE THREAD

**Issue by ClemensAtElektor** [arduino-libraries/PortentaX86#1]
It still refers to Faux86. Here is what I made of it:

```
name=Portenta86
version=1.0.0
author=Arduino
maintainer=Arduino <info@arduino.cc>
sentence=X86 emulator for Portenta H7
paragraph=
category=Display
url=https://github.com/arduino-libraries/PortentaX86
architectures=mbed,mbed_portenta

```

Also: category is Display?

**Comment by dcuartielles** [comment]
name should be PortentaX86

regarding the category, we need to figure out a new category for this
library, since it is an emulator (yet using a display)

**Comment by ClemensAtElektor** [comment]
Corrected on my side

**Comment by per1234** [comment]
>name should be PortentaX86

Shouldn't it be **Arduino_PortentaX86**? Arduino's policy is that all new official libraries should use the **Arduino_** prefix on their names.

The repository should also be renamed.

**Comment by dcuartielles** [comment]
I think we should involve @Martino Facchin ***@***.***> since it
is his making. I agree with @per123

**Comment by facchinm** [comment]
Feel free to post a PR, I'll be happy to merge :slightly_smiling_face:

**Comment by dcuartielles** [comment]
But the name change is on you @Martino Facchin ***@***.***> , I
don't think we can change it, or?

**Comment by ClemensAtElektor** [comment]
> Feel free to post a PR, I'll be happy to merge 🙂

I don't know what's right, I only know that what it is now is probably wrong.

**Comment by per1234** [comment]
I submitted PRs to resolve the issues reported here:

- https://github.com/arduino-libraries/Arduino_PortentaX86/pull/2
- https://github.com/arduino-libraries/Arduino_PortentaX86/pull/3

Reviews are welcome. Thanks for bringing this to our attention @ClemensAtElektor!

**Comment by per1234** [comment]
@facchinm this issue can be closed as resolved (I don't have any permissions in this repo so I can't do it).
